SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT ID 
    FROM (SELECT * FROM SKILLCODES WHERE CATEGORY = 'Front End') S, DEVELOPERS D
    WHERE S.CODE & D.SKILL_CODE != 0
) != 0
ORDER BY ID
